
name: Build and Deploy the Backend to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: jetrr-raahem-nabeel-1 # TODO: update Google Cloud project id
  GAR_LOCATION: us-central1 # TODO: update Artifact Registry location
  SERVICE: imsbackend # TODO: update Cloud Run service name
  REGION: us-central1 # TODO: update Cloud Run service region
  REPOSITORY: gcr.io
  IMAGE_URL: gcr.io/jetrr-raahem-nabeel-1/imsbackend
  IMAGE: imsbackend
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1  
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
      - name: Docker Auth
        run: |
          gcloud auth configure-docker gcr.io


      - name: Build and Push Docker Image
        working-directory: ./backend
        run: | 
          docker build --platform linux/amd64 -t gcr.io/jetrr-raahem-nabeel-1/imsbackend:test-git .
          docker push gcr.io/jetrr-raahem-nabeel-1/imsbackend:test-git                      


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy imsbackend \
            --image gcr.io/jetrr-raahem-nabeel-1/imsbackend:test-git \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --port=3000

      - name: Show Output
        run: echo "Deployment complete"
