name: Build and Deploy the Frontend to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: jetrr-raahem-nabeel-1 # Google Cloud project id
  GAR_LOCATION: us-central1 # Artifact Registry location
  SERVICE: imsfrontend   #Cloud Run service name
  REGION: us-central1   #Cloud Run service region
  REPOSITORY: gcr.io
  IMAGE_URL: gcr.io/jetrr-raahem-nabeel-1/imsfrontendfinal1
  IMAGE: imsfrontendfinal1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
        

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1  
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    
      - name: Docker Auth
        run: |
          gcloud auth configure-docker gcr.io

          
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        working-directory: ./frontend/image-search
        run: | 
          docker build --platform linux/amd64 -t ${{env.REPOSITORY}}/${{env.PROJECT_ID}}/${{env.IMAGE}}:${{github.sha}} .
          docker push ${{env.REPOSITORY}}/${{env.PROJECT_ID}}/${{env.IMAGE}}:${{github.sha}}                  


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{env.SERVICE}} \
            --image ${{env.REPOSITORY}}/${{env.PROJECT_ID}}/${{env.IMAGE}}:${{github.sha}}  \
            --region ${{env.REGION}} \
            --platform managed \
            --allow-unauthenticated \
            --port=3000

      - name: Show Output
        run: echo "Deployment complete"
